# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '货到付款'), (2, '支付宝')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(6, '已取消'), (2, '待发货'), (1, '待支付'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态'),
        ),
    ]
