# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-13 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180713_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(2, '支付宝'), (1, '货到付款')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(4, '待评价'), (3, '待收货'), (5, '已完成'), (2, '待发货'), (1, '待支付'), (6, '已取消')], default=1, verbose_name='订单状态'),
        ),
    ]
