# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180706_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsspecification',
            name='desc_detail',
        ),
        migrations.RemoveField(
            model_name='goodsspecification',
            name='desc_pack',
        ),
        migrations.RemoveField(
            model_name='goodsspecification',
            name='desc_service',
        ),
    ]
